# Data
raw_dataset_path: data/raw/Training Data.csv
dataset_path: data/output/data.pkl

predictors_set_path: data/output/predictors.pkl
response_set_path: data/output/response.pkl

train_path: 
- 'data/output/X_train.pkl'
- 'data/output/y_train.pkl'
test_path: 
- 'data/output/X_test.pkl' 
- 'data/output/y_test.pkl'

data_train_path: 'data/output/data_train.pkl'
data_train_binned_path: 'data/output/data_train_binned.pkl'

crosstab_list_path: 'data/output/crosstab_list.pkl'
WOE_table_path: 'data/output/WOE_table.pkl'
IV_table_path: 'data/output/IV_table.pkl'

WOE_map_dict_path: 'data/output/WOE_map_dict.pkl'
X_train_woe_path: 'data/output/X_train_woe.pkl'

# Variables
response_variable: 'risk_flag'
test_size: 0.3

num_columns: 
- 'income'
- 'age'
- 'experience'
- 'current_job_years'
- 'current_house_years'
cat_columns: 
- 'married'
- 'house_ownership'
- 'car_ownership'
- 'profession'
- 'city'
- 'state'
num_of_bins: 4

# Models
num_of_cv: 10
scoring: 'recall'

forward_models_path: models/forward_models.pkl
best_predictors_path: models/best_predictors_path.pkl
best_model_path: models/best_model.pkl
best_model_summary_path: models/best_model_summary.pkl

# Scorecards
pdo: 20
score_ref: 300
odds_ref: 30

scorecards_path: models/scorecards.pkl
points_map_dict_path: models/points_map_dict.pkl
X_points_path: models/X_points.pkl
X_train_points_path: models/X_train_points.pkl

score_path: models/score_path.pkl


# api.py related
cutoff_score: 150

columns_:
- 'income_bin'
- 'age_bin'
- 'experience_bin'
- 'current_job_years_bin'
- 'current_house_years_bin'
- 'married'
- 'house_ownership'
- 'car_ownership'
- 'profession'
- 'city'
- 'state'